version: '3.8'

services:
  rapidsai:
    build:
      context: .
      dockerfile: ./Dockerfile
    runtime: nvidia  # Specify NVIDIA runtime for GPU support
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Utilize all visible NVIDIA GPUs
    ports:
      - "5000:5000"

    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
