version: '3.8'

services:
  rapidsai:
    build:
      context: .
      dockerfile: ./Dockerfile
    runtime: nvidia  # Specify NVIDIA runtime for GPU support
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Utilize all visible NVIDIA GPUs
    ports:
      - "5000:5000"

    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
  
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=bdshare
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    networks:
      - mongo_net

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:

networks:
  mongo_net:
    driver: bridge
